services:
  - type: web
    name: heart-disease-predictor
    env: docker
    plan: free
    region: oregon  # any other available region
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
